# Generated by Django 4.2.11 on 2025-12-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareerApplication',
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
