# Generated by Django 4.2.11 on 2025-12-18 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreapi', '0003_alter_userprofile_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('folder', 'Folder')], max_length=20)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pinned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapi.userprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('file', 'File')], default='text', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapi.userprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
