# Generated by Django 4.2.11 on 2025-12-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0003_alter_userprofile_password'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='file_path',
            new_name='attached_path',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='message_type',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attached_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attached_type',
            field=models.CharField(choices=[('none', 'None'), ('file', 'File'), ('folder', 'Folder')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_messages', to='coreapi.userprofile'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='PinnedItem',
        ),
    ]
