# Generated by Django 4.2.11 on 2025-12-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ph_no', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('field_exec', 'Field Executive'), ('valuer', 'Valuation Officer'), ('staff', 'Staff Member')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
