# Generated by Django 4.2.11 on 2025-12-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0002_userprofile_password_alter_userprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
