# Generated by Django 4.2.11 on 2025-12-22 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0003_alter_userprofile_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFeedback',
            fields=[
                ('feedback_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('submission_number', models.IntegerField(default=1)),
                ('original_feedback_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office_file_no', models.CharField(blank=True, max_length=100, null=True)),
                ('applicant_name', models.CharField(blank=True, max_length=200, null=True)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('person_met', models.CharField(blank=True, max_length=200, null=True)),
                ('product', models.CharField(blank=True, max_length=50, null=True)),
                ('documents_received', models.JSONField(blank=True, default=list)),
                ('owners_name', models.TextField(blank=True, null=True)),
                ('ownership_verification', models.JSONField(blank=True, default=list)),
                ('ownership_notes', models.TextField(blank=True, null=True)),
                ('survey_data', models.JSONField(blank=True, default=dict)),
                ('survey_notes', models.TextField(blank=True, null=True)),
                ('boundary_data', models.JSONField(blank=True, default=dict)),
                ('boundary_notes', models.TextField(blank=True, null=True)),
                ('demarcation_north', models.JSONField(blank=True, default=list)),
                ('demarcation_east', models.JSONField(blank=True, default=list)),
                ('demarcation_south', models.JSONField(blank=True, default=list)),
                ('demarcation_west', models.JSONField(blank=True, default=list)),
                ('demarcation_notes', models.TextField(blank=True, null=True)),
                ('subject_encroachment', models.TextField(blank=True, null=True)),
                ('neighbor_encroachment', models.TextField(blank=True, null=True)),
                ('access_deed', models.JSONField(blank=True, default=list)),
                ('access_site', models.JSONField(blank=True, default=list)),
                ('private_users', models.JSONField(blank=True, default=list)),
                ('private_demarcation', models.JSONField(blank=True, default=list)),
                ('main_access_width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vehicular_access', models.JSONField(blank=True, default=list)),
                ('internal_road_width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('internal_connectivity', models.TextField(blank=True, null=True)),
                ('road_material', models.JSONField(blank=True, default=list)),
                ('access_notes', models.TextField(blank=True, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=200, null=True)),
                ('buyer_seller_relation', models.CharField(blank=True, max_length=200, null=True)),
                ('property_sale_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_method', models.TextField(blank=True, null=True)),
                ('purchase_land_extent', models.CharField(blank=True, max_length=100, null=True)),
                ('price_asked', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('deal_breaker_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('purchase_notes', models.TextField(blank=True, null=True)),
                ('building_floors_data', models.JSONField(blank=True, default=dict)),
                ('building_analysis_notes', models.TextField(blank=True, null=True)),
                ('roof_data', models.JSONField(blank=True, default=dict)),
                ('setback_data', models.JSONField(blank=True, default=dict)),
                ('construction_timeline', models.TextField(blank=True, null=True)),
                ('amenities_notes', models.TextField(blank=True, null=True)),
                ('landmark_description', models.TextField(blank=True, null=True)),
                ('sketch_image', models.ImageField(blank=True, null=True, upload_to='feedback_sketches/')),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='feedback_pdfs/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='coreapi.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by', '-created_at'], name='coreapi_sit_created_79618a_idx'), models.Index(fields=['office_file_no'], name='coreapi_sit_office__60efe2_idx'), models.Index(fields=['applicant_name'], name='coreapi_sit_applica_6c71f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAutoSave',
            fields=[
                ('autosave_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('form_data', models.JSONField(default=dict)),
                ('sketch_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autosaves', to='coreapi.userprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='coreapi_fee_user_id_24bad5_idx')],
            },
        ),
    ]
