# Generated by Django 4.2.11 on 2025-12-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0004_sitefeedback_feedbackautosave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitefeedback',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='FeedbackAutoSave',
        ),
        migrations.DeleteModel(
            name='SiteFeedback',
        ),
    ]
