# Generated by Django 4.2.11 on 2025-12-23 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coreapi', '0005_remove_sitefeedback_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office_file_no', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('applicant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('form_data', models.JSONField(default=dict)),
                ('sketch', models.ImageField(blank=True, null=True, upload_to='site_sketches/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
